version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=shorterurls
    # volumes:
    #   - postgres-data:/bitnami/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
#     volumes:
#       - redis-data:/bitnami/redis/data

# volumes:
#   postgres-data:
#   redis-data:
    
    